version: '3.8'

services:
  # django:
  #   build: .
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - redis
  #   environment:
  #     - DJANGO_SETTINGS_MODULE=image_labeling_backend.settings
  #   command: >
  #     sh -c "python manage.py migrate &&
  #            daphne -b 0.0.0.0 -p 8000 image_labeling_backend.asgi:application"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
