# Generated by Django 5.1.2 on 2025-02-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinate',
            name='include',
            field=models.BooleanField(default=False),
        ),
    ]
