# Generated by Django 5.1.2 on 2025-01-11 12:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_imagemodel_alter_coordinate_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagemodel",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to=api.models.thumbnail_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="imagemodel",
            name="image",
            field=models.ImageField(upload_to=api.models.image_upload_path),
        ),
    ]
