# Generated by Django 5.1.2 on 2025-02-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_coordinate_include'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coordinate',
            unique_together={('include', 'x', 'y')},
        ),
    ]
