# Generated by Django 5.1.2 on 2025-02-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_coordinate_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coordinate',
            unique_together=set(),
        ),
    ]
